version: "3.9"

services:
  openWebUI:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "3011:8080"
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      - ./.local-vol/open-webui-local:/app/backend/data

  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.local-vol/ollama-local:/root/.ollama

volumes:
  ollama-local:
    external: true
  open-webui-local:
    external: true